import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// cannot use css import with `tsx ./custom_server.ts`
// can only use `next dev`
// -- unless build the full thing in webpack + module.css support guess // no_knowlres

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      {/* <body>{children}</body> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
