import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

// import { SessionProvider } from 'next-auth/react';
import NextAuthSessionProvider from '@/libFix/NextAuthSessionProvider';
// ok indeed this is for the client side ...
// no need this if just use in the serverside ...

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* {children} */}
        <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
      </body>
    </html>
  );
}
